export const NAVIGATION_RING_DIAMETER = 44;
export const NAVIGATION_RING_RADIUS = 20;
export const NAVIGATION_RING_STROKE = 4;
export const NAVIGATION_DOT_DIAMETER = 10;
export const NAVIGATION_DOT_RADIUS = NAVIGATION_DOT_DIAMETER / 2;
export const NAVIGATION_SLIDE_STEP = 36;
export const NAVIGATION_ACTIVE_SCALE = 1.1;
export const NAVIGATION_SNAP_DISTANCE = 10;
export const NAVIGATION_BREAKAWAY_DISTANCE = 50;
export const NAVIGATION_RETURN_DELAY = 140;

export const NAVIGATION_SVG_SIZE = 52;
export const NAVIGATION_SVG_CENTER = NAVIGATION_SVG_SIZE / 2;
export const SECTION_NAVIGATION_ARROW_SIZE = 16;
export const SECTION_NAVIGATION_CENTERED_STEP = 60;
